// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Profile struct {
	ID     string `json:"ID"`
	Name   string `json:"name"`
	Tag    string `json:"tag"`
	Avatar string `json:"avatar"`
}

type Question struct {
	ID          string    `json:"id"`
	Content     string    `json:"content"`
	RecipientID string    `json:"recipientId"`
	CreatedAt   time.Time `json:"createdAt"`
}
